#!/usr/bin/env python3
"""Build the external-flash asset blob for the diagnostic firmware.

Combines a folder of your own audio files and one image into a single
binary, plus a matching Core/Inc/sound_assets.h offset table. Neither the
source files nor the generated blob are committed to this repo -- only this
script is. See assets/README.md for the full workflow.

Requires: ffmpeg, ffprobe, and the Pillow Python package (pip install pillow).

Usage:
    python3 build_assets.py --sounds-dir /path/to/your/wavs \\
        --image /path/to/your/image.png \\
        --out-bin assets/assets.bin \\
        --out-header ../Core/Inc/sound_assets.h
"""
import argparse
import os
import struct
import subprocess


def probe_duration(path):
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", path],
        capture_output=True, text=True, check=True).stdout.strip()
    return float(out)


def convert_to_pcm(src_path, out_path, sample_rate, channels):
    subprocess.run(
        ["ffmpeg", "-y", "-i", src_path, "-ar", str(sample_rate),
         "-ac", str(channels), "-f", "s16le", "-acodec", "pcm_s16le",
         out_path],
        capture_output=True, check=True)


def build_sounds(sounds_dir, work_dir, sample_rate, channels, max_seconds):
    """Returns list of (offset, length) and the concatenated PCM bytes."""
    files = sorted(f for f in os.listdir(sounds_dir)
                    if f.lower().endswith((".wav", ".mp3", ".flac", ".ogg")))
    offsets, lengths = [], []
    blob = bytearray()
    for fn in files:
        src = os.path.join(sounds_dir, fn)
        dur = probe_duration(src)
        if dur > max_seconds:
            print(f"skip (over {max_seconds}s cutoff): {fn} ({dur:.2f}s)")
            continue
        tmp = os.path.join(work_dir, "tmp.pcm")
        convert_to_pcm(src, tmp, sample_rate, channels)
        data = open(tmp, "rb").read()
        pad = (-len(data)) % 4
        offsets.append(len(blob))
        lengths.append(len(data))
        blob += data + b"\x00" * pad
        print(f"added: {fn} ({dur:.2f}s, {len(data)} bytes)")
    return offsets, lengths, bytes(blob)


def build_image(image_path, size, transparent_color):
    from PIL import Image
    img = Image.open(image_path).convert("RGBA").resize((size, size), Image.LANCZOS)
    pixels = img.load()
    out = bytearray()
    for y in range(size):
        for x in range(size):
            r, g, b, a = pixels[x, y]
            rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            if a < 128:
                rgb565 = transparent_color
            out += struct.pack("<H", rgb565)
    return bytes(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sounds-dir", required=True)
    ap.add_argument("--image", required=True)
    ap.add_argument("--out-bin", default="assets/assets.bin")
    ap.add_argument("--out-header", default="../Core/Inc/sound_assets.h")
    ap.add_argument("--sample-rate", type=int, default=48000,
                     help="Must match SND_SAMPLE_RATE_HZ / MX_SAI1_Init() in main.c")
    ap.add_argument("--channels", type=int, default=1,
                     help="Must match hsai_BlockA1.Init.MonoStereoMode in main.c (mono=1)")
    ap.add_argument("--max-seconds", type=float, default=2.5)
    ap.add_argument("--image-size", type=int, default=140)
    args = ap.parse_args()

    work_dir = os.path.dirname(os.path.abspath(args.out_bin)) or "."
    os.makedirs(work_dir, exist_ok=True)

    offsets, lengths, sounds_blob = build_sounds(
        args.sounds_dir, work_dir, args.sample_rate, args.channels, args.max_seconds)

    transparent_color = 0xF81F  # magenta sentinel, see assets/README.md
    image_offset = len(sounds_blob)
    image_blob = build_image(args.image, args.image_size, transparent_color)

    with open(args.out_bin, "wb") as f:
        f.write(sounds_blob)
        f.write(image_blob)

    with open(args.out_header, "w") as h:
        h.write("/* Generated by assets/build_assets.py. Do not hand-edit. */\n")
        h.write("#pragma once\n#include <stdint.h>\n\n")
        h.write(f"#define SOUND_COUNT {len(offsets)}\n\n")
        h.write("static const uint32_t sound_offsets[SOUND_COUNT] = {\n  ")
        h.write(",\n  ".join(f"{o}u" for o in offsets))
        h.write("\n};\n\n")
        h.write("static const uint32_t sound_lengths[SOUND_COUNT] = {\n  ")
        h.write(",\n  ".join(f"{l}u" for l in lengths))
        h.write("\n};\n\n")
        h.write(f"#define IMAGE_OFFSET {image_offset}u\n")
        h.write(f"#define IMAGE_WIDTH  {args.image_size}\n")
        h.write(f"#define IMAGE_HEIGHT {args.image_size}\n")
        h.write(f"#define IMAGE_TRANSPARENT_COLOR 0x{transparent_color:04X}u\n")

    total = len(sounds_blob) + len(image_blob)
    print(f"\nWrote {args.out_bin} ({total} bytes) and {args.out_header}")
    print(f"Flash with: gnwmanager erase --location ext && "
          f"gnwmanager flash --location ext --file {args.out_bin}")


if __name__ == "__main__":
    main()
